name: horizontal_center_date_picker
description: A flutter widget provides a horizontal date picker and always aligns selected date in center.
version: 2.1.1
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  intl: ^0.17.0  

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
